package by.gto.jasperprintmysql;

import by.gto.tools.ConfigReader;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author Aleks
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
        this.setTitle("Настройки");
        URL iconURL = getClass().getResource("/piggy-bank-icon.png");
        ImageIcon icon = new ImageIcon(iconURL);
        setIconImage(icon.getImage());
        jTextFieldIP.setText(ConfigReader.getInstance().getHost());
        jTextFieldPosition.setText(ConfigReader.getInstance().getPosition());
        jTextFieldСhiefDS.setText(ConfigReader.getInstance().getChiefDS());
        jSpinnerNDS.setValue(ConfigReader.getInstance().getNDS());
        //Отоброжение по центру экрана
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldIP = new javax.swing.JTextField();
        jTextFieldPosition = new javax.swing.JTextField();
        jTextFieldСhiefDS = new javax.swing.JTextField();
        jLabelIP = new javax.swing.JLabel();
        jLabelPort = new javax.swing.JLabel();
        jLabelСhiefDS = new javax.swing.JLabel();
        jLabelNDS = new javax.swing.JLabel();
        jSpinnerNDS = new javax.swing.JSpinner();
        jButtonSave = new javax.swing.JButton();
        jLabelResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabelIP.setLabelFor(jTextFieldIP);
        jLabelIP.setText("IP адрес сервера");

        jLabelPort.setLabelFor(jTextFieldPosition);
        jLabelPort.setText("Должность лица, составившего отчет");
        jLabelPort.setToolTipText("");

        jLabelСhiefDS.setLabelFor(jLabelСhiefDS);
        jLabelСhiefDS.setText("ФИО лица, составившего отчет");

        jLabelNDS.setText("НДС %");

        jSpinnerNDS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));

        jButtonSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonSave.setText("Сохранить");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jLabelResult.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelResult.setForeground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldСhiefDS)
                    .addComponent(jTextFieldPosition, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSpinnerNDS, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIP)
                            .addComponent(jTextFieldIP, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPort)
                            .addComponent(jLabelNDS)
                            .addComponent(jLabelСhiefDS))
                        .addGap(0, 97, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelIP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelСhiefDS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldСhiefDS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNDS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerNDS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonSave)
                        .addComponent(jLabelResult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        ConfigReader.getInstance().setHost(jTextFieldIP.getText().trim());
        ConfigReader.getInstance().setPosition(jTextFieldPosition.getText().trim());
        ConfigReader.getInstance().setChiefDS(jTextFieldСhiefDS.getText().trim());
        ConfigReader.getInstance().setNDS((int) jSpinnerNDS.getValue());
        ConfigReader.getInstance().setSave();
        jLabelResult.setText("<html><div align='center'>Успешно сохранено</div>");
    }//GEN-LAST:event_jButtonSaveActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabelIP;
    private javax.swing.JLabel jLabelNDS;
    private javax.swing.JLabel jLabelPort;
    private javax.swing.JLabel jLabelResult;
    private javax.swing.JLabel jLabelСhiefDS;
    private javax.swing.JSpinner jSpinnerNDS;
    private javax.swing.JTextField jTextFieldIP;
    private javax.swing.JTextField jTextFieldPosition;
    private javax.swing.JTextField jTextFieldСhiefDS;
    // End of variables declaration//GEN-END:variables
}
